sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - pip install coveralls
  - LC_ALL=C pip install .
script:
  - coverage run setup.py test
  - coverage report --fail-under=90
after_success:
  - coveralls
